### ISSUE TITLE
can i use transform-orign?

### ISSUE THREAD

**Issue by ouzhou** [MellowMelon/canvas-transform#1]
like css, can i use transform-origin to matrix()?

**Comment by MellowMelon** [comment]
Sorry for the delayed response. No, canvas contexts require you to simulate transform-origin's effects yourself. Since a canvas lets you do all kinds of drawing commands while transform-origin is applied to a single DOM element, it makes more sense in CSS. You only have to do one computation for the size of that DOM element. In canvas it might have a different effect on each individual command, which defeats the purpose of it being a low-level API.

To simulate it, do a translation relative to the size of whatever you want to draw.
